# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
 require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
     '#{script}',
     {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
setup_permissions([
 # 'AppTrackingTransparency',
 # 'Bluetooth',
 # 'Calendars',
 # 'CalendarsWriteOnly',
  'Camera',
 # 'Contacts',
 # 'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
 # 'Microphone',
 # 'Motion',
  'Notifications',
  'PhotoLibrary'
 # 'PhotoLibraryAddOnly',
 # 'Reminders',
 # 'Siri',
 # 'SpeechRecognition',
 # 'StoreKit',
])
platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
# flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
 Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
 use_frameworks! :linkage => linkage.to_sym
end

target 'LawnQ' do
 config = use_native_modules!
 pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
 pod 'GoogleMaps'
 pod 'Google-Maps-iOS-Utils'
 pod 'GoogleAppMeasurement'
 pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
 pod 'lottie-ios', :path => '../node_modules/lottie-ios'
 pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'


#  pod 'Firebase/Auth', '10.29.0'
#  pod 'Firebase/Storage', '11.5.0'
#  pod 'Firebase/Core', '11.5.0'
# pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
 # Flags change depending on the env values.
 flags = get_default_flags()
 use_frameworks! :linkage => :static
 use_react_native!(
   :path => config[:reactNativePath],
   # Hermes is now enabled by default. Disable by setting this flag to false.
   :hermes_enabled => true,
   :fabric_enabled => flags[:fabric_enabled],
   # Enables Flipper.
   #
   # Note that if you have use_frameworks! enabled, Flipper will not work and
   # you should disable the next line.
   # :flipper_configuration => flipper_config,
   # An absolute path to your application root.
   :app_path => "#{Pod::Config.instance.installation_root}/.."
 )
 


 target 'LawnQTests' do
  inherit! :complete
  # Pods for testing
end

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
end
end

